### PR TITLE
added float32 and float64 compatibility

### PR DESCRIPTION
**Pull request by kash1102**

### CODE REVIEW

**Comment by kash1102** [comment]
@richardjgowers could you please guide me regarding the errors I could not figure out my mistake since I only made changes to 3 files core.pyx , cgmath.pyx and capped_distance.py .
Thanks :)

**Comment by richardjgowers** [comment]
@kash1102 looks like a problem with travis rather than this fix.  You'll need to change the existing tests so they test both precisions we support

**Comment by kash1102** [comment]
@richardjgowers I have changed the test files to test both precisions kindly look the changes once.
any inputs on the changes will be highly appreciated.

Thanks :)

**Comment by orbeckst** [comment]
Do you know why the tests failed?

**Comment by richardjgowers** [comment]
Ok I fixed the tests on the master branch, can you rebase onto it and force push to this PR? (`git fetch` and update your version of master, `git rebase master` from this branch, then `git push -f` to this PR)

**Pull request closed without merging**
